# Generated by Django 4.2 on 2023-06-03 17:32

from django.db import migrations
import projekt.models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='korisnik',
            managers=[
                ('objects', projekt.models.KorisnikManager()),
            ],
        ),
    ]
