# Generated by Django 4.2 on 2023-06-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0002_alter_korisnik_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kolegij',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolegij_text', models.CharField(max_length=255)),
            ],
        ),
    ]
