# Generated by Django 4.2.1 on 2023-07-25 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0003_kolegij'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obavijest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=2000)),
                ('publication_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('kolegij', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.kolegij')),
            ],
        ),
    ]
