# Generated by Django 4.2.1 on 2023-07-25 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0004_obavijest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kolegij',
            name='kolegij_text',
        ),
        migrations.AddField(
            model_name='kolegij',
            name='kolegij_naziv',
            field=models.CharField(default='Default Name', max_length=255),
        ),
        migrations.AddField(
            model_name='kolegij',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projekt.profesor'),
        ),
    ]
