# Generated by Django 4.2.1 on 2023-07-27 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0005_remove_kolegij_kolegij_text_kolegij_kolegij_naziv_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kolegij',
            options={'verbose_name_plural': 'Kolegiji'},
        ),
        migrations.AlterModelOptions(
            name='obavijest',
            options={'verbose_name_plural': 'Obavijesti'},
        ),
        migrations.AddField(
            model_name='obavijest',
            name='autor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
