# Generated by Django 4.2.2 on 2023-07-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0007_remove_obavijest_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obavijest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
