# Generated by Django 4.2.2 on 2023-07-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0008_alter_obavijest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kolegij',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
