# Generated by Django 4.2.2 on 2023-07-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0009_alter_kolegij_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obavijest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
