# Generated by Django 4.2.2 on 2023-07-27 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0010_alter_obavijest_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kolegij',
            old_name='id',
            new_name='kolegij_id',
        ),
    ]
