# Generated by Django 4.2.2 on 2023-07-27 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0011_rename_id_kolegij_kolegij_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obavijest',
            name='kolegij',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projekt.kolegij'),
        ),
    ]
